### ISSUE TITLE
Black borers on rotate

### ISSUE THREAD

**Issue by ThiloL** [claviska/SimpleImage#84] opened 2015-05-30 13:37 UTC
If I rotate small (150px) pictures I get black borders in resulting files.

**Comment by claviska** [comment] 2015-05-30 14:18
Sounds like a duplicate of #40.

**Comment by ThiloL** [comment] 2015-05-30 17:03
No I have only rotated by 90/270 degree's.

**Comment by claviska** [comment] 2015-05-30 18:26
Can you post the image and some code please?






— Cory LaViska




A Beautiful Site, LLC

www.abeautifulsite.net

**Comment by claviska** [comment] 2015-08-31 22:00
Closing due to inactivity. If this is still an issue, please post a minimal test case so we an reproduce and troubleshoot.

**Closed by claviska** 2015-08-31 22:00 UTC
