### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'SimpleImage' not found in 

### ISSUE THREAD

**Issue by barnamah** [claviska/SimpleImage#285] opened 2021-09-02 18:13 UTC
Hello,
I have SimpleImage.php  version     **2.5.5** and in the same folder I have . If I don't included it inside a function it works. 
I am using it like this and it **works perfectly. Thank you.** 

```php
$img->load($sourceFile)->fit_to_width($STNG['ThumbWidth'])->save($newThumbFile);

$img->load($sourceFile)->best_fit($STNG['prodImageWidthMax'], $STNG['prodImageHeightMax'])->save($newFile);
```

I am using it in my test.php file like this

```php
function makeThumb() {
  require 'SimpleImage.php';
  $img = new  SimpleImage();// make img object      
}
```

it gives error. Then in a page people mention to use

```php
require 'SimpleImage.php';
$img = new  abeautifulsite\SimpleImage();// make img object      
```

still no luck. 

I tried to use your new SimpleImage class but you don't have single example to initiate object where wen can use it. Now it is almost a week I am struggling with this. Please help. 

Suggestion:

Please make example like above in a file. I learned it from the old SimpleImage.php class.
Thanks

**Comment by claviska** [comment] 2021-09-02 18:21
Does the example in the readme not work for you? https://github.com/claviska/SimpleImage#overview

**Comment by barnamah** [comment] 2021-09-02 18:28
No it does not. has >fromFile('image.jpg')  I don't know how to use. like the above. I am using it in a loop over wither 1600 image. 
the >fromFile('image.jpg')  is confusing. 
so why I am I getting error?

**Comment by barnamah** [comment] 2021-09-02 18:36
it says
$image
    ->fromFile('image.jpg')                     // load image.jpg
    ->autoOrient()                              // adjust orientation based on exif data
    ->resize(320, 200)                          // resize to 320x200 pixels
    ->flip('x')                                 // flip horizontally
    ->colorize('DarkBlue')                      // tint dark blue
    ->border('black', 10)                       // add a 10 pixel black border
    ->overlay('watermark.png', 'bottom right')  // add a watermark image
    ->toFile('new-image.png', 'image/png')      // convert to PNG and save a copy to new-image.png
    ->toScreen();                               // output to the screen
there is not best fit. Also why you used namespace. it should have been simple class with functions. 
I have also posted similar question here [https://stackoverflow.com/questions/69034772/simpleimage-php-is-not-working-when-included](url)

**Comment by claviska** [comment] 2021-09-02 21:11
Please follow the example and review the current API docs and ensure you’re using the current version. You seem to be mixing up the old abeautifulsite namespace with the new one.

I can confirm that the example shown works, as does the one in `/example/index.php`. As this tracker is for bugs and features, and since you have an open issue on SO, I’m going to close this question out.

**Closed by claviska** 2021-09-02 21:11 UTC
Labels: Question
