### ISSUE TITLE
Colors changing

### ISSUE THREAD

**Issue by gventuri** [claviska/SimpleImage#208] opened 2017-10-07 13:28 UTC
Hello there! Great tool!

Unfortunately I'm having an issue. Some users made me notice before, but I thought that was depending on their screen calibration.

Yesterday a user shared with me some screens of his photo before/after the upload on my website, and at that point I started to investigate. 

This is difference of the photo before and after the upload:
![screen shot 2017-10-07 at 15 18 53](https://user-images.githubusercontent.com/15671184/31308249-a07d2ea6-ab73-11e7-8558-6441591c9759.png)

This is my script, in case you need it:

      $file = "https://example.com/my-photo.jpg";
      
      $img = new \claviska\SimpleImage();
      $img->fromFile($file);
      $img->autoOrient();
   
      <img src="<?=$img->toDataUri()?>" alt="Test 2" width="40%">

Now, as you can see there's a huge difference between the 2 photos. Now my question is: am I doing something wrong or this is a bug?

Thank you for your availability.

**Comment by claviska** [comment] 2017-10-07 15:57
That’s a good question — I haven’t seen this before. Does it happen with PNGs as well, or just JPEGs?

Unfortunately, this is most likely a GD issue since `autoOrient()` just runs a rotation. It may help to know your GD version and have copies of the original image so I can test it myself. I’ve seen a handful of GD oddities that happen in older versions, so it can help rule things out.

I’m happy to look into this and run some tests if you can provide that.

**Comment by gventuri** [comment] 2017-10-07 16:52
I tried also without auto-rotation, and it happens as well!
It happens for sure with jpeg, haven't tried with png yet, as our website doesn't allow pngs. I'll try and let you know the results.

At the moment, I can't share the image as I don't have the rights, but I can ask the owner if he allows me.

The current version of the GD is 2.1.1.

**Comment by claviska** [comment] 2017-10-07 17:12
Yep, rotation doesn’t likely have anything to do with it. It sounds like GD is doing something funny when it reads or writes the image.

**Comment by claviska** [comment] 2017-10-09 14:04
I tested this with the original image you sent me privately and I can confirm the same result. I also tried converting it to a PNG first (outside of SimpleImage) and got the same results.

I'm leaving this open as a "help wanted" because this doesn't appear to be a bug in SimpleImage, but GD itself. My assumption is based on the fact that, internally, SimpleImage is opening the image with `imagecreatefromjpeg()` and saving it with `imagejpeg()`, so there's not much that could be going wrong in there.

Maybe someone with more knowledge of GD knows why this is happening. Maybe it's a palette bug or some kind of color correction thing happening in GD.

**Comment by gventuri** [comment] 2017-11-02 21:47
Found this: https://bugs.php.net/bug.php?id=53598 It seems it's a problem of how GD handle some profile images where resizing. Any possible workarounds coming into your mind?

**Comment by claviska** [comment] 2017-11-03 14:15
Definitely looks like a GD issue. See also: https://github.com/libgd/libgd/issues/136

This is a wontfix because it needs to be fixed upstream.

**Closed** 2017-11-03 14:15 UTC
Labels: Question

**Comment by gventuri** [comment] 2017-11-03 17:59
It seems this could be fixed with a script like this (https://github.com/slavicv/jpeg-icc/blob/master/class.jpeg_icc.php), which can get the color profile of the original photo and apply to the final image. Do you think that would be easily implementable in the resize function before returning the result? The other option, obviously, might be to move to ImageMagick, but that's something I'd like to avoid!

**Comment by claviska** [comment] 2017-11-03 21:42
I'd like to avoid adding such a dependency — it doesn't look like it's maintained. SimpleImage is effectively a GD wrapper and this is something that really should be fixed upstream. Have you posted your support there?

Maybe you could detect affected images and regenerate them without the color profile as a workaround.

**Comment by gventuri** [comment] 2017-11-03 23:52
Yeah, I think I'll do that, it's the best thing to do.
Thank you very much for the support. I think you can close the topic, thanks!
