### ISSUE TITLE
Thumbnail method loses transparency

### ISSUE THREAD

**Issue by Poldan** [claviska/SimpleImage#192] opened 2017-07-04 09:40 UTC
Transparent color is replaced by black:

```php
$img = new claviska\SimpleImage();
$img
  ->fromFile('1.png')
  ->thumbnail(500,500)
  ->toFile('1_.png','image/png');
```
Another method (resize, bestFit) works right.

**Comment by claviska** [comment] 2017-07-04 14:06
Can't reproduce. Can you provide some sample code and a source image?

**Comment by Poldan** [comment] 2017-07-05 03:51
https://transfer.sh/2KDox/test.tar.gz
Sample code.

**Comment by claviska** [comment] 2017-07-05 14:43
This must be something specific to do with your GD version, because it's working properly for me.

Resulting image:

![test](https://user-images.githubusercontent.com/55639/27869497-1e08711e-616e-11e7-8e47-af70ab414325.png)

What version of PHP and GD do you have? You can find this info with a quick call to [`phpinfo()`](http://php.net/phpinfo).

It's working properly with PHP 7.1.0 and GD 2.1.0:

![screen shot 2017-07-05 at 10 41 14 am](https://user-images.githubusercontent.com/55639/27869657-9a881b40-616e-11e7-825d-a41f6ec38728.png)

**Comment by claviska** [comment] 2017-07-05 14:47
Note: I've edited your comments to use proper code formatting and embedded the test case here (you can't always rely on third-party sites to keep things online).

To format code blocks, use [GitHub Flavored Markdown](https://github.github.com/gfm/). For example:

![screen shot 2017-07-05 at 10 45 55 am](https://user-images.githubusercontent.com/55639/27869836-2840a434-616f-11e7-9c7b-bf90c59d7e6b.png)

Always try to post the minimum required code to reproduce the problem. This makes it easier for maintainers to help you and future visitors to understand what's going on. 😎

**Comment by Poldan** [comment] 2017-07-06 01:05
GD library Version | 2.2.3
PHP 5.6

**Comment by claviska** [comment] 2017-07-06 13:24
That's really strange. If anything, you'd think it would be the other way around.

Unfortunately, this is clearly outside of SimpleImage. It may be worth posting an issue with the [GD project](https://github.com/libgd/libgd), but I'm sure they'll want us to test on the latest and greatest. Problem is, most people using PHP don't know how (or can't) update GD so that won't really do much.

If you have the time and want to narrow it down to the exact method that's causing this, I can toss some more ideas around. Internally, the [thumbnail](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L974-L986) method uses [resize](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L747-L756) and [crop](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L536-L546). Both are pretty straightforward, but I suspect [this code](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L777-L792) may have something to do with it.

**Comment by Poldan** [comment] 2017-07-11 03:55
[This line](https://github.com/claviska/SimpleImage/blob/master/src/claviska/SimpleImage.php#L554)
I think, this brokes transparent color.

**Comment by claviska** [comment] 2017-08-31 00:49
Closing because this is outside of SimpleImage – likely due to a specific GD version since I'm unable to replicate. No other reports, either.

**Closed by claviska** 2017-08-31 00:49 UTC
Labels: Bug
